copyright: Copyright (c) 2017-2020 peepslabs and its contributors.  All rights reserved.
theme: fullwidth
github_url: https://github.com/ARISENIO/arisen-swift
github_file_prefix: https://github.com/ARISENIO/arisen-swift/tree/master
hide_documentation_coverage: true
undocumented_text: ""
output: docs
clean: true
custom_categories:
  - name: Transactions
    children:
    - ArisenTransaction
    - ArisenTransactionFactory
  - name: Provider Protocols
    children:
    - ArisenSignatureProviderProtocol
    - ArisenSerializationProviderProtocol
    - ArisenAbiProviderProtocol
    - ArisenRpcProviderProtocol
  - name: Built-In Default Providers
    children:
    - ArisenRpcProvider
    - ArisenAbiProvider
  - name: General Helpers & Types
    children:
    - ArisenName
    - ArisenResult
    - RIPEMD160
    - JsonOutput
    - Base58String
    - Queue
    - LinkedList
    - Node
  - name: Extensions
    children:
    - Array
    - Data
    - Date
    - Dictionary
    - Encodable
    - Resolver
    - String
  - name: Errors
    children:
    - ArisenError
    - ArisenErrorCode
    - Error
  - name: Signature Provider Types
    children:
    - ArisenAvailableKeysResponse
    - ArisenTransactionSignatureRequest
    - ArisenTransactionSignatureResponse
  - name: RPC Provider Protocols
    children:
    - ArisenRpcResponseProtocol
    - ArisenRpcInfoResponseProtocol
    - ArisenRpcBlockResponseProtocol
    - ArisenRpcRawAbiResponseProtocol
    - ArisenRpcRequiredKeysResponseProtocol
    - ArisenRpcTransactionResponseProtocol
  - name: Default RPC Requests
    children:
    - ArisenRpcAbiRequest
    - ArisenRpcAccountRequest
    - ArisenRpcHistoryActionsRequest
    - ArisenRpcBlockHeaderStateRequest
    - ArisenRpcBlockRequest
    - ArisenRpcCodeRequest
    - ArisenRpcHistoryControlledAccountsRequest
    - ArisenRpcCurrencyBalanceRequest
    - ArisenRpcCurrencyStatsRequest
    - ArisenRpcHistoryTransactionRequest
    - ArisenRpcHistoryKeyAccountsRequest
    - ArisenRpcProducersRequest
    - ArisenRpcPushTransactionRequest
    - ArisenRpcPushTransactionsRequest
    - ArisenRpcRawAbiRequest
    - ArisenRpcRawCodeAndAbiRequest
    - ArisenRpcRequiredKeysRequest
    - ArisenRpcTableByScopeRequest
    - ArisenRpcTableRowsRequest
  - name: Default RPC Responses
    children:
    - ArisenRpcAbiResponse
    - ArisenRpcAccountResponse
    - ArisenRpcActionsResponse
    - ArisenRpcBlockHeaderStateResponse
    - ArisenRpcBlockResponse
    - ArisenRpcCodeResponse
    - ArisenRpcControlledAccountsResponse
    - ArisenRpcCurrencyBalanceResponse
    - ArisenRpcCurrencyStatsResponse
    - ArisenRpcGetTransactionResponse
    - ArisenRpcKeyAccountsResponse
    - ArisenRpcInfoResponse
    - ArisenRpcProducersResponse
    - ArisenRpcTransactionResponse
    - ArisenRpcPushTransactionsResponse
    - ArisenRpcRawAbiResponse
    - ArisenRpcRawCodeAndAbiResponse
    - ArisenRpcRequiredKeysResponse
    - ArisenRpcTableByScopeResponse
    - ArisenRpcTableRowsResponse
  - name: Other RPC-Related Types
    children:
    - RawResponse
    - ArisenUInt64
    - ArisenAccountInfo
    - ArisenRpcActionsResponseAction
    - ArisenRpcActionsResponseActionTrActDeltas
    - ArisenRpcActionsResponseActionTrReceipt
    - ArisenRpcActionsResponseActionTrace
    - ArisenRpcActionsResponseActionTraceAction
    - ArisenRpcActionsResponseActionTraceAuth
    - ArisenRpcBlockHeaderStateResponseHeader
    - Authority
    - CurrencyStats
    - KeyWeight
    - Permission
    - PermissionLevel
    - PermissionLevelWeight
    - ProducerRows
    - TableByScopeRows
    - WaitWeight
