language: swift
xcode_workspace: ArisenSwift.xcworkspace
xcode_scheme: ArisenSwiftTests
osx_image: xcode10.2
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone 5s
before_install:
- pod repo update
- pod install